const { createCanvas, loadImage } = require("canvas");
const path = require("node:path");

class SecurityExportService {
    csv(rows) {
        const columns = ["user", "result", "reason", "timestamp", "attempts", "durationSeconds"];
        const escape = value => {
            let safe = String(value ?? "");
            if (/^[=+\-@]/.test(safe)) safe = `'${safe}`;
            return `"${safe.replaceAll('"', '""')}"`;
        };
        return `\uFEFF${columns.join(",")}\r\n${rows.map(row => columns.map(column => escape(row[column])).join(",")).join("\r\n")}`;
    }

    async pdf(guild, report) {
        const canvas = createCanvas(612, 792, "pdf");
        const context = canvas.getContext("2d");
        context.fillStyle = "#090b10"; context.fillRect(0, 0, 612, 792);
        const gradient = context.createLinearGradient(0, 0, 612, 0); gradient.addColorStop(0, "#00d9ff"); gradient.addColorStop(1, "#bc37ff");
        context.fillStyle = gradient; context.fillRect(0, 0, 612, 8);
        try { const logo = await loadImage(path.join(__dirname, "../dashboard/public/gatekeeper-logo.png")); context.drawImage(logo, 42, 34, 62, 62); } catch {}
        context.fillStyle = "#f5f7fb"; context.font = "bold 24px Arial"; context.fillText("SentraGuard Security Report", 122, 58);
        context.fillStyle = "#8f9bad"; context.font = "12px Arial"; context.fillText(guild.name, 122, 81);
        context.fillText(`${new Date(report.range.startMs).toLocaleDateString()} - ${new Date(report.range.endMs).toLocaleDateString()}`, 42, 125);
        const cards = [["Attempts", report.current.total], ["Success rate", `${report.current.successRate}%`], ["Failures", report.current.failures], ["Raid alerts", report.raidAlerts]];
        cards.forEach(([label, value], index) => { const x = 42 + index * 132; context.fillStyle = "#151a24"; context.fillRect(x, 150, 120, 78);
            context.fillStyle = "#8f9bad"; context.font = "10px Arial"; context.fillText(label, x + 12, 171); context.fillStyle = "#f5f7fb"; context.font = "bold 24px Arial"; context.fillText(String(value), x + 12, 207); });
        context.fillStyle = "#f5f7fb"; context.font = "bold 16px Arial"; context.fillText("Security and member journey", 42, 275);
        const metrics = [["Account-risk flags", report.accountRisk], ["Trusted bypasses", report.trusted], ["Manual verifications", report.manual],
            ["Reverifications enforced", report.reverifications], ["Onboarding deliveries", report.onboarding.total], ["Onboarding failures", report.onboarding.failures]];
        metrics.forEach(([label, value], index) => { const y = 305 + index * 38; context.fillStyle = index % 2 ? "#10151e" : "#131923"; context.fillRect(42, y, 528, 32);
            context.fillStyle = "#c5cad4"; context.font = "11px Arial"; context.fillText(label, 54, y + 20); context.fillStyle = "#7cf0bd"; context.font = "bold 12px Arial"; context.fillText(String(value), 528, y + 20); });
        context.fillStyle = "#f5f7fb"; context.font = "bold 16px Arial"; context.fillText("Top failure reasons", 42, 566);
        report.failures.slice(0, 5).forEach((row, index) => { const y = 596 + index * 27; context.fillStyle = "#8f9bad"; context.font = "10px Arial"; context.fillText(String(row.reason).slice(0, 62), 54, y); context.fillStyle = "#ff9ca5"; context.fillText(String(row.count), 540, y); });
        context.fillStyle = "#596579"; context.font = "9px Arial"; context.fillText("Privacy-safe aggregate report - Generated by SentraGuard / SecureBootLabs", 42, 758);
        return canvas.toBuffer("application/pdf", { title: `SentraGuard Security Report - ${guild.name}`, author: "SecureBootLabs" });
    }
}

module.exports = SecurityExportService;
